sso_auth_url:  https://arena.nafc.org.au/auth/realms/Arena/protocol/openid-connect/token
sso_auth_grant_type: password

arena_rest_api_root_url: https://arena.nafc.org.au/register/api/

report_completion_url: unsec/bcp/complete
report_completion_version: 2017-03

arena_apis:
  aircraft:
    file_name: aircraft.json
    url: aircraft?fields
    version: 2015-05
  equipment:
    file_name: equipment.json
    url: equipment?fields
    version: 2015-05
  dispatches:
    file_name: dispatches.json
    url: dispatches?fields
    version: 2015-05
  availability:
    file_name: availability.json
    url: availability
    version: 2016-01
  locations:
    file_name: locations.json
    url: locations
    version: 2017-01
  approvals:
    file_name: approvals.json
    url: approvals/aircraft?fields
    version: 2017-01
  callsigns:
    file_name: callsigns.json
    url: unsec/aircraftCallsigns
    version: 2017-02
