arena_rest_api_root_url: http://localhost:8080/register/api/

box_identifier: LOCAL

sso_auth_url: http://localhost:8080/ssodev/token

sso_auth_client_id: arena-api
sso_auth_client_secret: notused
sso_auth_username: localtest-bcpbox
sso_auth_password: localtest-bcpbox
